language: python
python: '2.7'
branches:
  only:
  - master
  - develop
install:
  - pip install pytest coverage codacy-coverage
script:
  - printenv
  - ls -la
  - coverage run -m py.test tests
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - python setup.py install
deploy:
  provider: pypi
  user: devopshq
  password:
    secure: "KBNBXu5h38LnDbQkjr0+2FqpU27Y0cwNjtG0x44tnsxQQOgnidU5r3khjqe7cpiOAySlU0yOarSH1Py7IJiRK2XpdYgRz6ZdM29nq9uJvdyQ9jNNgWAoXMl2olWRe5I2IcAvTQ8Dc5j8EmWmds2GuPFrSh3HAVjZXv4yGkY4bXsXlp1SHPTzJUbHQBntKQJLBVV6/jgCAJ6drHQLKSIx4zWaxub3OmePPC0/y4R4Qj/O+sfGMTdOnrNnNkzjEhAo3sxHn1lWlwit4Is6m7J5dA5m7G6jNNDqVJ+r+2b+q575NXKbSqurRqkVHiw7BplkD4vcImRlSilfI83cHyKA2j5qprI6jFakkjyu79zOaa7HuDnWBPbdIpT69F0de9iRPtdlivEyfo0Kmtg0VGUaJkb52QMO5SkdU7XpVRKzSIDvyUFwN7igsUoe052yISILpOk3Y5qjZq+Fsx7XgeZmF8tLGTdsHJIHFLwFHrQbozF9SEMEtuRFzpAGxwavmvgRcCAuR7HPfQxywE0a9dZyF4odGg8QwoCNzwVl5qsQFagCJ9RjDngTf3bcHcwaV35tIHxdmXijkdY1+d2vP7hu+b0EnMELSOTiYcjsmgBK3Mn45WzOoq/gCJdZ1AKjRdDylmcDLo7ddKvTpAgeZux/2r3MQ6tMLGH4bHcJcsA9XYc="
  distributions: bdist_wheel
  on:
    all_branches: true
  skip_cleanup: true
after_script:
  - echo "Deploy to PyPI finished."
env:
  global:
  - secure: "laINM+2dOwjZe1pw5pzt1f4L3Pqtd867taoFV+XSlqtxe1onyZje7x1iVbslmNdCTeo62Lidx9z9I3Vwv9dDBkjEfGwyUHHHz+kRwJ4zJbCQ4HzYQ6auIjP7MuyKsl6bysnKAdrjo/OtPX1a6iKKaIOv1RoDD4FQldps5Chl6GLJjbpsQPHn07vj2XvcDQcMQH0AFBxIROAxQir1Ox01LLsC2DxiCxQ4QxosLBjv0Gat1h7bT7bKu74qV+OPo5VNPg/H4/u+fIirx8V6r0HHXsoFEhlyYkKSvAfYljyZREUwI8cuu1Q463CBstHH4IokEDzhZO0hJrgLPYnNJyNhgfc3BEgRAiCVOplWBXjvk5k+Fi8NeogvbS4dNExt6am1sy9iKml2p34aErVgh5RVFYrezAJlUPDTcGSOW6eXUfl62ORDbvXth48lbbzxqOi9iTu6UduImTAKuyK0rnQcRTSfRHKqoo/Ptc+p5tJoAU/NKoaJRmYdC0taXJCLWFZqZl7n/ERaknUFBmmmBunmgQ38t3T1Qt9UMdzYshxNSoonTNJELlcRlRZLrZAl0w0BW1SNkB636yku2s9a0gidi25JK+Hx0Mquax0Y+I0bKhxiwVFI/2bCZQyJxGVRzm/elsQzFmIiUBbB4mcfdJpxeZ/2SdVPiPT0pwqY7oVLOks="